### ISSUE TITLE
No se renderiza la pantalla para agregar estudiantes

### ISSUE THREAD

**Issue by faloi** [mumuki/mumuki-platform#272]
Esto veo cuando clickeo en "Agregar estudiante":

![image](https://cloud.githubusercontent.com/assets/1585835/26594188/01752362-4567-11e7-9c3a-bf6c99b15e98.png)

Y al abrir la consola aparece este error:

```
vendor-e37bd3e82e.js:15 ReferenceError: laboratoryURL is not defined
    at Object.tosURL (http://alcal-prog3.classroom.mumuki.io/scripts/main-cb199a7012.js:2:22644)
    at Object.tosUrl (http://alcal-prog3.classroom.mumuki.io/scripts/main-cb199a7012.js:2:25911)
    at new <anonymous> (http://alcal-prog3.classroom.mumuki.io/scripts/main-cb199a7012.js:1:28069)
    at i (http://alcal-prog3.classroom.mumuki.io/scripts/vendor-e37bd3e82e.js:14:24683)
    at Object.o [as instantiate] (http://alcal-prog3.classroom.mumuki.io/scripts/vendor-e37bd3e82e.js:14:24775)
    at http://alcal-prog3.classroom.mumuki.io/scripts/vendor-e37bd3e82e.js:15:14750
    at http://alcal-prog3.classroom.mumuki.io/scripts/vendor-e37bd3e82e.js:19:26683
    at rt (http://alcal-prog3.classroom.mumuki.io/scripts/vendor-e37bd3e82e.js:15:10609)
    at m (http://alcal-prog3.classroom.mumuki.io/scripts/vendor-e37bd3e82e.js:15:4521)
    at s (http://alcal-prog3.classroom.mumuki.io/scripts/vendor-e37bd3e82e.js:15:713) <section ui-view="content" class="content ng-scope">
```

**Comment by fedescarpa** [comment]
fixed in https://github.com/mumuki/mumuki-classroom/commit/78d8294d839714ef1a4058ca0cbd83a5a8124929
